### ISSUE TITLE
Error connecting to sqlserver2008

### ISSUE THREAD

**Issue by wenbin151** [actframework/act-ebean#18]
Configuration:

```
db.db2.impl=act.db.ebean.EbeanPlugin
db.db2.url=jdbc:sqlserver://172.168.1.110;databasename=erpdb;autoReconnect=true;selectmethod=cursor
db.db2.username=sa
db.db2.password=1234
db.db2.databasePlatformName=sqlserver17
```

Error log:

```
org.osgl.exception.ConfigurationException: Error init SQL db service
	at org.osgl.util.E.invalidConfiguration(E.java:300)
	at act.db.sql.SqlDbService$1.run(SqlDbService.java:121)
	at act.db.sql.SqlDbService$1.on(SqlDbService.java:82)
	at act.event.EventBus.callOn(EventBus.java:1312)
	at act.event.EventBus.access$1400(EventBus.java:53)
	at act.event.EventBus$4.run(EventBus.java:1341)
	at act.job.JobManager$ContextualJob$1.apply(JobManager.java:460)
	at act.job.Job.doJob(Job.java:350)
	at act.job.Job.run(Job.java:287)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.persistence.PersistenceException: java.lang.IllegalArgumentException: For SqlServer please explicitly choose either sqlserver16 or sqlserver17 as the platform via ServerConfig.setDatabasePlatformName. Refer to issue #1340 for more details
	at io.ebeaninternal.server.core.DatabasePlatformFactory.create(DatabasePlatformFactory.java:66)
	at io.ebeaninternal.server.core.DefaultContainer.setDatabasePlatform(DefaultContainer.java:270)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:130)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:45)
	at io.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:109)
	at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:70)
	at act.db.ebean.EbeanService.dataSourceProvided(EbeanService.java:114)
	at act.db.sql.SqlDbService.doInitDataSource(SqlDbService.java:263)
	at act.db.sql.SqlDbService.initDataSource(SqlDbService.java:245)
	at act.db.sql.SqlDbService.access$000(SqlDbService.java:54)
	at act.db.sql.SqlDbService$1.run(SqlDbService.java:95)
	... 15 common frames omitted
Caused by: java.lang.IllegalArgumentException: For SqlServer please explicitly choose either sqlserver16 or sqlserver17 as the platform via ServerConfig.setDatabasePlatformName. Refer to issue #1340 for more details
	at io.ebeaninternal.server.core.DatabasePlatformFactory.byDatabaseMeta(DatabasePlatformFactory.java:144)
	at io.ebeaninternal.server.core.DatabasePlatformFactory.byDataSource(DatabasePlatformFactory.java:123)
	at io.ebeaninternal.server.core.DatabasePlatformFactory.create(DatabasePlatformFactory.java:63)
	... 25 common frames omitted
```

**Comment by wenbin151** [comment]
Caused by: javax.persistence.PersistenceException: java.lang.IllegalArgumentException: For SqlServer please explicitly choose either sqlserver16 or sqlserver17 as the platform via ServerConfig.setDatabasePlatformName. Refer to issue #1340 for more details

**Comment by wenbin151** [comment]
跟踪代码是发现initDataSource 在dataSourceProvided时没有把sqlserver2008特有的参数databasePlatformName独立传递给DataSourceConfig dsConfig带入到这个方法里面，而是放在了customProperties里面，ebeanConfig创建数据库🔗时没有单独处理customProperties里面的参数。所以报上文错误

**Comment by wenbin151** [comment]
at io.ebeaninternal.server.core.DatabasePlatformFactory.create(DatabasePlatformFactory.java:63)中
public DatabasePlatform create(ServerConfig serverConfig) {
...
serverConfig.getDatabasePlatformName()  没有拿到这个配置，所以抛错
...
}

**Comment by wenbin151** [comment]
act 1.8.8.6  act-bean1.7.3  测试ok。启动没有错误，读取数据ok。

**Comment by greenlaw110** [comment]
reopen it till the version is released
