### ISSUE TITLE
Homepage configuration get error

### ISSUE THREAD

**Issue by fliu721** [actframework/act-ebean#31]
When I want to config the ebean's ServerConfig, I found the document on this:
`https://github.com/actframework/act-ebean2#configuration`
But after add the method in one of my class, the application will got a error when stating, the full error stack is like this:
```
2018-12-10 14:02:24,095 WARN  a.j.Job@[jobs-thread-2] - error executing job SimpleEventListenerByteCodeScanner:bindEventListener:SimpleEventListenerByteCodeScanner:init:com.github.fliu.config.ebean.EbeanConfig.configureEbean
org.osgl.exception.UnexpectedException: Invalid event type: class io.ebean.config.ServerConfig
	at org.osgl.util.E.unexpected(E.java:179)
	at act.event.EventBus$Key.typeOf(EventBus.java:117)
	at act.event.EventBus$Key.setId(EventBus.java:103)
	at act.event.EventBus$Key.<init>(EventBus.java:73)
	at act.event.EventBus._bind(EventBus.java:1193)
	at act.event.EventBus.bind(EventBus.java:597)
	at act.event.bytecode.SimpleEventListenerByteCodeScanner$1.run(SimpleEventListenerByteCodeScanner.java:73)
	at act.job.Job$4.apply(Job.java:442)
	at act.job.Job.doJob(Job.java:403)
	at act.job.Job.run(Job.java:338)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:112)
	at act.job.Job$LockableJobList.runSubJobs(Job.java:93)
	at act.job.Job.runPrecedenceJobs(Job.java:419)
	at act.job.Job.run(Job.java:330)
	at act.job.JobManager$_SysEventListener.on(JobManager.java:477)
	at act.event.EventBus.callOn(EventBus.java:1354)
	at act.event.EventBus.callOn(EventBus.java:1376)
	at act.event.EventBus.callOn(EventBus.java:1406)
	at act.event.EventBus._emit(EventBus.java:1267)
	at act.event.EventBus.emit(EventBus.java:723)
	at act.app.App.emit(App.java:1240)
	at act.app.App$3.run(App.java:758)
	at act.job.JobManager$ContextualJob$1.apply(JobManager.java:528)
	at act.job.Job.doJob(Job.java:403)
	at act.job.Job.run(Job.java:338)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by greenlaw110** [comment]
The issue is superseded by #33
