### ISSUE TITLE
DocStore implementation not included in the classPath. You need to add the maven dependency for avaje-ebeanorm-elastic

### ISSUE THREAD

**Issue by wuuJiawei** [actframework/act-ebean#34]
When creating a query with multi condition, the application throw this exception
```
调用请求处理器 xyz.easyboot.module.console.controller.RoleController.listByModel 时发生错误: Conflict
 - java.lang.IllegalStateException: DocStore implementation not included in the classPath. You need to add the maven dependency for avaje-ebeanorm-elastic
```

Here is the error stack
```
at io.ebeanservice.docstore.none.NoneDocStore.implementationNotInClassPath(NoneDocStore.java:22)
at io.ebeanservice.docstore.none.NoneDocStore.findList(NoneDocStore.java:82)
at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1573)
at io.ebeaninternal.server.core.DefaultServer.findList(DefaultServer.java:1554)
at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findList(DefaultOrmQuery.java:1543)
at xyz.easyboot.module.console.controller.RoleController.listByModel(RoleController.java:38)
at xyz.easyboot.module.console.controller.RoleControllerMethodAccess.invoke(Unknown Source)
at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:1090)
at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.invoke(ReflectedHandlerInvoker.java:1076)
at act.handler.builtin.controller.impl.ReflectedHandlerInvoker.handle(ReflectedHandlerInvoker.java:706)
at act.handler.builtin.controller.ControllerAction.handle(ControllerAction.java:49)
at act.handler.builtin.controller.RequestHandlerProxy._handle(RequestHandlerProxy.java:569)
at act.handler.builtin.controller.RequestHandlerProxy.handle(RequestHandlerProxy.java:211)
at act.app.ActionContext.proceedWithHandler(ActionContext.java:1423)
at act.route.Router$ContextualHandler.handle(Router.java:1771)
at act.xio.NetworkHandler$3.run(NetworkHandler.java:191)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by wuuJiawei** [comment]
Try to add dependency of avaje-ebeanorm-elastic
```
    <dependency>
      <groupId>org.avaje.ebeanorm</groupId>
      <artifactId>avaje-ebeanorm-elastic</artifactId>
      <version>1.3.1</version>
    </dependency>
```
But nothing happened

**Comment by wuuJiawei** [comment]
My code
```
    @Inject
    private EbeanDao<Integer, SysRole> dao;

    @GetAction("list2/m")
    public Iterable<SysRole> listByModel() {
        return dao.q().where().like("role_name", "用户").and().eq("id", "id").order().desc("id").findList();
    }
```
