### ISSUE TITLE
Todo-Ebean sample project start failure on JDK 15

### ISSUE THREAD

**Issue by greenlaw110** [actframework/act-ebean#35]
Error stack:

```
Caused by: io.ebean.config.BeanNotEnhancedException: Bean class demo.todo.ebean.TodoItem is not enhanced? Check packages specified in ebean.mf. If you are running in IDEA or Eclipse check that the enhancement plugin is installed. See https://ebean.io/docs/trouble-shooting#not-enhanced
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.setEntityBeanClass(BeanDescriptorManager.java:1580)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.createByteCode(BeanDescriptorManager.java:1445)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.readDeployAssociations(BeanDescriptorManager.java:1354)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.readEntityDeploymentAssociations(BeanDescriptorManager.java:770)
	at io.ebeaninternal.server.deploy.BeanDescriptorManager.deploy(BeanDescriptorManager.java:374)
	at io.ebeaninternal.server.core.InternalConfiguration.<init>(InternalConfiguration.java:198)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:124)
	at io.ebeaninternal.server.core.DefaultContainer.createServer(DefaultContainer.java:35)
	at io.ebean.EbeanServerFactory.createInternal(EbeanServerFactory.java:109)
	at io.ebean.EbeanServerFactory.create(EbeanServerFactory.java:70)
	at act.db.ebean.EbeanService.dataSourceProvided(EbeanService.java:118)
	at act.db.sql.SqlDbService.doInitDataSource(SqlDbService.java:275)
	at act.db.sql.SqlDbService.initDataSource(SqlDbService.java:257)
	at act.db.sql.SqlDbService.init(SqlDbService.java:118)
```

The issue does not happen on JDK8

**Comment by greenlaw110** [comment]
The problem is in the `act.db.ebean.EbeanAgentLoader.loadAgentFromClasspath(...)` method. It assume it can find an instance of `URLClassLoader`, but it is not true when app is running on JDK9+.
